sudo: required

env:
  - secure: "YlFtTNvoxs6eBIQLD0tS1dU8EljCa/1QMJvhUyX87rj5XMpR1S85aBfVDvEJPuf6ul8su7k2a8ZyrPWzVTY0xRigwXIHQAmBZn1LyzLEfOUFoT5YKlfofuqwY/uGqM4dT2gtHgPoW29tPfMe4jgFWMsB2ehpAx+9399i6gDrPBkG3NC7gNk+q/A17A6lWRuVyTNIPOzuTEk0iNgbDtaiAfecY+E5vOAQhJlApVzgMvhZXzHQFy1WlbOw+T2451R4gbfeyvsE0mz4mwgcWTBSSaBUFceeaArOIv9vsKcIMNVQha3kzEsrFD51MFy06/faoKZXL0jMCANjPfXuJp1/EMiLM78lfAJ7IaAWi/qOzcTVuK+b2YC903n2jgdgT9/dK2e8r/dWy3JXNW7tbBZqusF3JE2NmzCLCbu/zg3aZABKjXq/9eyiuF7YuEga1hcVLE/lhOcTGn5q/toepugAo8EUuBmKVcNirOeK/rGgmGlKaNK2y78q1QbnNLV/hJrjAZu0iNQQNEKK6S8uO3AOsGNubYX1ew516nmKBd6gvhlTfek9N/4L0u5voWjfG7TPr791M7bStpmc7C1l6WBt4lOrzh8B3PCV0tKK89YWgnQNOVclQ4NjMMqChhwd1Q590vhVLgw73h/EOZbSPxF2UTsqYf8WyoZWI69pOXtjZCk="

services:
  - docker

install: make

before_script:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - make install_dependencies
  - make setup_credentials

script:
  - echo $PROJECT
  #- make test
  #- make lint
  #- make build_image
  #- make deploy_to_qa
  #- make deploy_to_prod BUILD_DEBUG=yes

after_script:
  - make clean_credentials

