"""empty message

Revision ID: 32d8259ad0ad
Revises: a69223b321c9
Create Date: 2018-05-14 01:46:51.301590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d8259ad0ad'
down_revision = 'a69223b321c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participantes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombres_completos', sa.String(length=200), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=15), nullable=True),
    sa.Column('inscripcion_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participantes')
    # ### end Alembic commands ###
