"""empty message

Revision ID: 3c9364b3654f
Revises: 4a2707f9b9d8
Create Date: 2018-06-18 20:24:56.872436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9364b3654f'
down_revision = '4a2707f9b9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscripciones', sa.Column('administradores', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inscripciones', 'administradores')
    # ### end Alembic commands ###
