"""empty message

Revision ID: 4a2707f9b9d8
Revises: a795d999adb8
Create Date: 2018-06-17 01:39:41.703260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2707f9b9d8'
down_revision = 'a795d999adb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participantes', sa.Column('fecha_inscripcion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participantes', 'fecha_inscripcion')
    # ### end Alembic commands ###
