"""empty message

Revision ID: 77ab2fce2113
Revises: b4f7dbf58a9a
Create Date: 2018-06-09 21:48:42.147889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ab2fce2113'
down_revision = 'b4f7dbf58a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('readable_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'readable_name')
    # ### end Alembic commands ###
