"""empty message

Revision ID: a13dcf7ce176
Revises: 3c9364b3654f
Create Date: 2018-07-14 18:31:15.169739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13dcf7ce176'
down_revision = '3c9364b3654f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preventas_camiseta',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombres_completos', sa.String(length=200), nullable=False),
    sa.Column('localidad', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('talla', sa.String(length=2), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_deposito', sa.Date(), nullable=False),
    sa.Column('numero_deposito', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preventas_camiseta')
    # ### end Alembic commands ###
